# Generated by Django 5.2 on 2025-05-02 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakuro_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kakuropuzzle',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10),
        ),
    ]
