# Generated by Django 5.2 on 2025-05-10 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minewordle_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='word',
            table='words',
        ),
    ]
