# Generated by Django 5.2 on 2025-05-11 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minewordle_app', '0003_score'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='score',
            table='scores',
        ),
    ]
