# Generated by Django 5.2 on 2025-05-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tents_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tentspuzzle',
            name='col_hints',
        ),
        migrations.RemoveField(
            model_name='tentspuzzle',
            name='grid',
        ),
        migrations.RemoveField(
            model_name='tentspuzzle',
            name='row_hints',
        ),
        migrations.AddField(
            model_name='tentspuzzle',
            name='board_data',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='tentspuzzle',
            name='col_clues',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='tentspuzzle',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10),
        ),
        migrations.AddField(
            model_name='tentspuzzle',
            name='layout',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='tentspuzzle',
            name='row_clues',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='tentspuzzle',
            name='solution',
            field=models.JSONField(default=list),
        ),
    ]
